//
// Created by xdbeef on 11.04.18.
//

#ifndef SPELUNKYDS_SPRITETYPES_H
#define SPELUNKYDS_SPRITETYPES_H

enum SpriteType{
    MAIN_DUDE,
    MENU_SIGNS_TUTORIAL_QUIT,
    MENU_SIGNS_START_SCORES,
    BOMB,
    ROCK,
    JAR,
    MONIEZ_TRIPLE_GOLD_BARS,
    MONIEZ_RUBY_BIG,
    SNAKE,
    ROPES,
    ROPE_ELEMENT,
    PRE_WHIP,
    WHIP,
    HUD,
    BLOOD,
    SPELUNKY_TITLE,
    SPELUNKY_COPYRIGHTS,
    BAT,
    SPIDER
};

#endif //SPELUNKYDS_SPRITETYPES_H
