//
// Created by xdbeef on 11.04.18.
//

#ifndef SPELUNKYDS_SPRITETYPES_H
#define SPELUNKYDS_SPRITETYPES_H

enum SpriteType{
    MAIN_DUDE,
    BOMB,
    ROCK,
    JAR,
    MONIEZ_TRIPLE_GOLD_BARS,
    MONIEZ_RUBY_BIG,
    SNAKE,
    ROPES,
    ROPE_ELEMENT,
    PRE_WHIP,
    WHIP,
    HUD_HEART,
    HUD_DOLLAR,
    HUD_BOMB,
    HUD_ROPE,
    HUD_HOLDING_ITEM,
    BLOOD
};

#endif //SPELUNKYDS_SPRITETYPES_H
