//
// Created by xdbeef on 24.02.18.
//

#ifndef SPELUNKYDS_SCREENPOSITIONS_H
#define SPELUNKYDS_SCREENPOSITIONS_H

enum ScreenPositions{
    SCREEN_TOP = 0, SCREEN_BOTTOM = 192, SCREEN_LEFT = 0, SCREEN_RIGHT = 256
};

#endif //SPELUNKYDS_SCREENPOSITIONS_H
