//
// Created by dbeef on 4/20/19.
//

#ifndef SPELUNKYDS_MAINDUDECONSTS_H
#define SPELUNKYDS_MAINDUDECONSTS_H

static const float MAIN_DUDE_MAX_X_SPEED = 2;
static const float MAIN_DUDE_MAX_X_SPEED_CRAWLING = 1.5f;
static const float MAIN_DUDE_MAX_X_SPEED_RUNNING = 3;
static const float MAIN_DUDE_MAX_Y_SPEED = 3.3f;
static const float MAIN_DUDE_MAX_Y_SPEED_USING_CAPE = 1.7f;
static const float MAIN_DUDE_JUMP_SPEED = 2.55f;

static const u16 MAIN_DUDE_MIN_HANGING_TIME = 100;
static const u16 MAIN_DUDE_STUN_TIME = 2000;
static const u16 MAIN_DUDE_STUN_FALLING_TIME = 900;
static const u16 MAIN_DUDE_PUSHING_TIME = 500;
static const u16 MAIN_DUDE_DAMAGE_PROTECTION_TIME = 1500;
static const u16 MAIN_DUDE_FRAMES_PER_ANIMATION = 6;
static const u16 MAIN_DUDE_HITPOINTS = 4;
static const u16 MAIN_DUDE_SPRITESHEET_ROW_WIDTH = 6;
static const u16 MAIN_DUDE_X_SPEED_DELTA_TIME_MS = 2;
static const u16 MAIN_DUDE_X_SPEED_DELTA_VALUE = 2;
static const u16 MAIN_DUDE_FRICTION_DELTA_SPEED = 1;


static const u16 MAIN_DUDE_MENU_START_POSITION_X = 224;
static const u16 MAIN_DUDE_MENU_START_POSITION_Y = 300;

static const u16 CAMERA_MENU_START_X = 0;
static const u16 CAMERA_MENU_START_Y = 127;


#endif //SPELUNKYDS_MAINDUDECONSTS_H
